# Use Windows bridge as host inventory
# Windows bridge will need PowerCLI installed
---
- name: Update Secondary Cluster
  hosts: secondary
  serial: 1
  gather_facts: no
  roles:
    - common

- name: Update Primary Cluster
  hosts: primary
  gather_facts: no
  serial: 1
  roles:
    - common
