---
- name: Install Ansible Prerequisites
  apt:
    name:
      - python3-pip
      - libssl-dev
      - libkrb5-dev
    update_cache: yes

- name: Install Ansible via pip3
  pip:
    executable: pip3
    name:
      - ansible
      - pywinrm[kerberos]
      - pyvmomi
