---
- name: Install Rundeck Repositories
  apt_repository:
    repo: deb https://rundeck.bintray.com/rundeck-deb
    state: present
    filename: rundeck.list

- name: Add Rundeck repo key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    state: present

- name: Install Rundeck and Nginx
  apt:
    name:
      - rundeck
      - nginx
    update_cache: yes

- name: Copy certificate
  copy: src={{ item.src }} dest={{ item.dest }} mode='0400'
  with_items:
    - { src: 'files/server_cert.pem', dest: '/opt/rundeck' }
    - { src: 'files/server_key.pem', dest: '/opt/rundeck' }

- name: Copy default site
  copy:
    src: files/default_site
    dest: /etc/nginx/sites-available/default

